### ISSUE TITLE
get_historical does not work

### ISSUE THREAD

**Issue by ifuchs** [condereis/realtime-stock#67]
>>> stock = Stock('AAPL')
>>> stock.get_historical('2016-03-01', '2016-03-02')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/rtstock/stock.py", line 230, in get_historical
    return request_historical(self.__ticker, start_date, end_date)
  File "//anaconda/lib/python2.7/site-packages/rtstock/utils.py", line 166, in request_historical
    'stock ticker used is a valid one.')
rtstock.error.RequestError: Unable to process the request. Check if the stock ticker used is a valid one.

**Comment by condereis** [comment]
I am currently not updating this project. In the future, when I have more time i may come back to it. Sorry :(
