### ISSUE TITLE
no longer working?

### ISSUE THREAD

**Issue by joeharr4** [condereis/realtime-stock#84]
I pip installed:

pip install realtime-stock
Collecting realtime-stock
  Downloading realtime-stock-1.0.0.tar.gz
Building wheels for collected packages: realtime-stock
  Running setup.py bdist_wheel for realtime-stock ... done
  Stored in directory: /root/.cache/pip/wheels/18/72/81/690321ae3aaea0793560cba96bbda12c6357b6f5e957a4564e
Successfully built realtime-stock
Installing collected packages: realtime-stock
Successfully installed realtime-stock-1.0.0

And ran it on:

Python 3.6.2 |Anaconda, Inc.| (default, Sep 30 2017, 18:42:57) 
[GCC 7.2.0] on linux

Under Ubuntu 16.04 LTS, latest updates.  I ran the example:

```
>>> from rtstock.stock import Stock
>>> stock = Stock('AAPL')

>>> stock.get_latest_price()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/rtstock/stock.py", line 92, in get_latest_price
    ['LastTradePriceOnly', 'LastTradeTime'])
  File "/usr/local/lib/python3.5/dist-packages/rtstock/utils.py", line 101, in request_quotes'    'columns selected are valid.')
rtstock.error.RequestError: Unable to process the request. Check if the columns selected are valid.

```
Similar problems are happening with ystockquote and googlefinance and yahoo-finance packages.  Both Yahoo! and Google have changed or shut down their APIs. Is there another source of data, such as the markets themselves or brokers (at least for their customers)? I see very little discussion of alternatives, but some, such as (scroll down a bit):

https://stackoverflow.com/questions/46080632/http-error-404-from-googlefinance-in-python-2-7/46081537#46081537

--jh--

**Comment by condereis** [comment]
I am currently not updating this project. In the future, when I have more time i may come back to it. Sorry :(
